project:
  type: book

book:
  title: "Julia 实践指南"
  language: "zh"
  author: "吴自华"
  reader-mode: true

  page-footer:
    left: |
      《Julia 实践指南》采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 协议授权
    right: |
      基于 <a href="https://quarto.org/">Quarto</a> 构建
  cover-image: cover.png
  favicon: logo.png
  repo-url: https://github.com/lucifer1004/julia-guide
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - part: starter/index.qmd
      chapters:
        - starter/version.qmd 
        - starter/installation.qmd
        - starter/environment.qmd

    - part: style/index.qmd
      chapters:
        - style/structure.qmd
        - style/style.qmd
        - style/reading.qmd
        - style/documentation.qmd
        - style/testing.qmd
        - style/logging.qmd
        - style/license.qmd

    - part: plotting/index.qmd
      chapters: 
        - plotting/plots.ipynb
        - plotting/makie.ipynb
        - plotting/gadfly.ipynb

    - part: 其他
      chapters: 
        - misc/hpc.qmd

    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: ctexbook
    pdf-engine: tectonic
